// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OBPostupyApi.Contexts;

namespace OBPostupyApi.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20220302214712_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.14");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int?>("RaceId")
                        .HasColumnType("int");

                    b.Property<string>("Sex")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("RaceId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.Control", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<string>("CoordinatesString")
                        .HasColumnType("longtext");

                    b.Property<int?>("CourseDataId")
                        .HasColumnType("int");

                    b.Property<string>("MapCoordinatesString")
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseDataId");

                    b.ToTable("Controls");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CourseDataId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CourseDataId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.CourseControl", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("ControlId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("CourseId", "ControlId", "Order");

                    b.HasIndex("ControlId");

                    b.ToTable("CourseControls");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.CourseData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RaceId")
                        .IsUnique();

                    b.ToTable("CourseData");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.CourseSplit", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("SplitId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "SplitId");

                    b.HasIndex("SplitId");

                    b.ToTable("CourseSplits");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<double?>("Elevation")
                        .HasColumnType("double");

                    b.Property<int>("PathId")
                        .HasColumnType("int");

                    b.Property<string>("PositionString")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PathId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.Map", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CornersString")
                        .HasColumnType("longtext");

                    b.Property<double>("East")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<double>("North")
                        .HasColumnType("double");

                    b.Property<string>("PathToFile")
                        .HasColumnType("longtext");

                    b.Property<int?>("RaceId")
                        .HasColumnType("int");

                    b.Property<double?>("Rotation")
                        .HasColumnType("double");

                    b.Property<int>("Scale")
                        .HasColumnType("int");

                    b.Property<double>("South")
                        .HasColumnType("double");

                    b.Property<double>("West")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.Path", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Paths");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("RegNumbers")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.PersonResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FinishTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PathId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PathId")
                        .IsUnique();

                    b.HasIndex("PersonId");

                    b.ToTable("PersonResults");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Organizer")
                        .HasColumnType("longtext");

                    b.Property<int>("OrisId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.Split", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CourseDataId")
                        .HasColumnType("int");

                    b.Property<int?>("FirstControlId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondControlId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseDataId");

                    b.HasIndex("FirstControlId");

                    b.HasIndex("SecondControlId");

                    b.ToTable("Splits");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.SplitTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<int>("PersonResultId")
                        .HasColumnType("int");

                    b.Property<int?>("SplitId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TimeSpan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonResultId");

                    b.HasIndex("SplitId");

                    b.ToTable("SplitTimes");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NickName")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RegNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OBPostupyApi.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OBPostupyApi.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OBPostupyApi.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OBPostupyApi.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OBPostupyApi.Entities.Category", b =>
                {
                    b.HasOne("OBPostupyApi.Entities.Course", "Course")
                        .WithMany("Categories")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OBPostupyApi.Entities.Race", "Race")
                        .WithMany("Categories")
                        .HasForeignKey("RaceId");

                    b.Navigation("Course");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.Control", b =>
                {
                    b.HasOne("OBPostupyApi.Entities.CourseData", "CourseData")
                        .WithMany("Controls")
                        .HasForeignKey("CourseDataId");

                    b.Navigation("CourseData");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.Course", b =>
                {
                    b.HasOne("OBPostupyApi.Entities.CourseData", "CourseData")
                        .WithMany("Courses")
                        .HasForeignKey("CourseDataId");

                    b.Navigation("CourseData");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.CourseControl", b =>
                {
                    b.HasOne("OBPostupyApi.Entities.Control", "Control")
                        .WithMany("CourseControl")
                        .HasForeignKey("ControlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OBPostupyApi.Entities.Course", "Course")
                        .WithMany("CourseControl")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Control");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.CourseData", b =>
                {
                    b.HasOne("OBPostupyApi.Entities.Race", "Race")
                        .WithOne("CourseData")
                        .HasForeignKey("OBPostupyApi.Entities.CourseData", "RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.CourseSplit", b =>
                {
                    b.HasOne("OBPostupyApi.Entities.Course", "Course")
                        .WithMany("CourseSplits")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OBPostupyApi.Entities.Split", "Split")
                        .WithMany("CourseSplits")
                        .HasForeignKey("SplitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Split");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.Location", b =>
                {
                    b.HasOne("OBPostupyApi.Entities.Path", "Path")
                        .WithMany("Locations")
                        .HasForeignKey("PathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Path");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.Map", b =>
                {
                    b.HasOne("OBPostupyApi.Entities.Race", "Race")
                        .WithMany("Maps")
                        .HasForeignKey("RaceId");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.PersonResult", b =>
                {
                    b.HasOne("OBPostupyApi.Entities.Category", "Category")
                        .WithMany("PersonResults")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OBPostupyApi.Entities.Path", "Path")
                        .WithOne("PersonResult")
                        .HasForeignKey("OBPostupyApi.Entities.PersonResult", "PathId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OBPostupyApi.Entities.Person", "Person")
                        .WithMany("PersonResults")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Path");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.Race", b =>
                {
                    b.HasOne("OBPostupyApi.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.Split", b =>
                {
                    b.HasOne("OBPostupyApi.Entities.CourseData", "CourseData")
                        .WithMany("Splits")
                        .HasForeignKey("CourseDataId");

                    b.HasOne("OBPostupyApi.Entities.Control", "FirstControl")
                        .WithMany("SplitsFirstControl")
                        .HasForeignKey("FirstControlId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OBPostupyApi.Entities.Control", "SecondControl")
                        .WithMany("SplitsSecondControl")
                        .HasForeignKey("SecondControlId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CourseData");

                    b.Navigation("FirstControl");

                    b.Navigation("SecondControl");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.SplitTime", b =>
                {
                    b.HasOne("OBPostupyApi.Entities.PersonResult", "PersonResult")
                        .WithMany("SplitTimes")
                        .HasForeignKey("PersonResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OBPostupyApi.Entities.Split", "Split")
                        .WithMany("SplitTimes")
                        .HasForeignKey("SplitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PersonResult");

                    b.Navigation("Split");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.Category", b =>
                {
                    b.Navigation("PersonResults");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.Control", b =>
                {
                    b.Navigation("CourseControl");

                    b.Navigation("SplitsFirstControl");

                    b.Navigation("SplitsSecondControl");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.Course", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("CourseControl");

                    b.Navigation("CourseSplits");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.CourseData", b =>
                {
                    b.Navigation("Controls");

                    b.Navigation("Courses");

                    b.Navigation("Splits");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.Path", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("PersonResult");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.Person", b =>
                {
                    b.Navigation("PersonResults");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.PersonResult", b =>
                {
                    b.Navigation("SplitTimes");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.Race", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("CourseData");

                    b.Navigation("Maps");
                });

            modelBuilder.Entity("OBPostupyApi.Entities.Split", b =>
                {
                    b.Navigation("CourseSplits");

                    b.Navigation("SplitTimes");
                });
#pragma warning restore 612, 618
        }
    }
}
